import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <header className={styles.background}>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__container}>
        <h2 className={styles.main__title}>Check out our latest article</h2>
        <ul className={styles.main__list}>
          <li className={styles.mainList__item}>
            <div className={styles.mainListItem__image}>
              <img src="/images/firstImage.png" alt="firstImage" />
            </div>
            <div className={styles.mainListItem__content}>
              <h4 className={styles.mainListItem__title}>
                Disease detection, check up in the laboratory
              </h4>
              <p className={styles.mainListItem__text}>
                In this case, the role of the health laboratory is very
                important to do a disease detection...
              </p>
              <button className={styles.mainListItem__btn}>
                Read more{" "}
                <img
                  className={styles.mainListItem__arrow}
                  src="/images/icons/arrowRight.png"
                  alt="arrow"
                />
              </button>
            </div>
          </li>
          <li className={styles.mainList__item}>
            <div className={styles.mainListItem__image}>
              <img src="/images/secondImage.png" alt="secondImage" />
            </div>
            <div className={styles.mainListItem__content}>
              <h4 className={styles.mainListItem__title}>
                Disease detection, check up in the laboratory
              </h4>
              <p className={styles.mainListItem__text}>
                Herbal medicine is very widely used at this time because of its
                very good for your health...
              </p>
              <button className={styles.mainListItem__btn}>
                Read more{" "}
                <img
                  className={styles.mainListItem__arrow}
                  src="/images/icons/arrowRight.png"
                  alt="arrow"
                />
              </button>
            </div>
          </li>
          <li className={styles.mainList__item}>
            <div className={styles.mainListItem__image}>
              <img src="/images/thirdImage.png" alt="thirdImage" />
            </div>
            <div className={styles.mainListItem__content}>
              <h4 className={styles.mainListItem__title}>
                Disease detection, check up in the laboratory
              </h4>
              <p className={styles.mainListItem__text}>
                A healthy lifestyle should start from now and also for your skin
                health. There are some...
              </p>
              <button className={styles.mainListItem__btn}>
                Read more{" "}
                <img
                  className={styles.mainListItem__arrow}
                  src="/images/icons/arrowRight.png"
                  alt="arrow"
                />
              </button>
            </div>
          </li>
        </ul>
      </main>
      <img
        className={styles.background__image}
        src="/images/background.png"
        alt="background"
      />
    </header>
  );
}
