import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.sass";
import axios from "../api/cart.news";

export default function Home() {
  const [cart, setCart] = useState([]);
  useEffect(() => {
    const getCart = async () => {
      try {
        const res = await axios.get(
          "/kartochkis?sort=publishedAt:DESC&pagination[pageSize]=3&populate=image"
        );
        if (!res.data) {
          throw new Error();
        }
        setCart([...res.data.data]);
      } catch (error) {
        console.log(error);
      }
    };
    getCart();
  }, []);
  return (
    <header className={styles.background}>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__container}>
        <h2 className={styles.main__title}>Check out our latest article</h2>
        <ul className={styles.main__list}>
          {cart.map(({ image, title, text }, index) => {
            return (
              <li key={index} className={styles.mainList__item}>
                <div className={styles.mainListItem__image}>
                  <img src={image.url} alt={image.name} />
                </div>
                <div className={styles.mainListItem__content}>
                  <h4 className={styles.mainListItem__title}>
                    {title}
                  </h4>
                  <p className={styles.mainListItem__text}>
                    {text}
                  </p>
                  <button className={styles.mainListItem__btn}>
                    Read more{" "}
                    <img
                      className={styles.mainListItem__arrow}
                      src="/images/icons/arrowRight.png"
                      alt="arrow"
                    />
                  </button>
                </div>
              </li>
            );
          })}
        </ul>
      </main>
      <img
        className={styles.background__image}
        src="/images/background.png"
        alt="background"
      />
    </header>
  );
}
